// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/bucket': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bucket/index.get').default>>>>
    }
    '/api/bucket/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bucket/upload.post').default>>>>
    }
    '/api/contact': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact.post').default>>>>
    }
    '/api/db/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/db/users.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/db/users.post').default>>>>
    }
    '/api/error-test': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/error-test').default>>>>
    }
    '/api/hello': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello').default>>>>
    }
    '/api/posts/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id].get').default>>>>
    }
    '/api/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.get').default>>>>
    }
    '/api/vectors/insert': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vectors/insert.post').default>>>>
    }
    '/api/vectors/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vectors/search.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}