// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/10/2026, 9:18:02 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/plugins/**/*.{js,ts,mjs}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/composables/**/**/*.{js,ts,mjs}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/composables/**/*.{js,ts,mjs}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/utils/**/*.{js,ts,mjs}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Demo-Nuxt/Demo-Nuxt/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;